### ISSUE TITLE
Plan first draft

### ISSUE THREAD

**Issue by zanerock** [liquid-labs/vulgar-sdlc#1]
## Overview

We want to abstract out the SDLC stuff from [`policy-projects`](https://github.com/liquid-labs/policy-projects) and move it here so that it's referenced and developed as a pure SDLC model. The policy will then pull in diagrams and text from this project.

## Deliverables

The basic deliverables here will be a `Vulgar PDLC Implementation Plan.md` file defines a series of tasks in the same format as our standard tasks, plus any additional overview and/or context documentation deemed useful. E.g., something like:
````markdown
# Vulgar PDLC Implementation Plan

## Overview

The basic plan is....

## Tasks

### Create project skeleton

```
## Overview

Let's lay stuff out!

## Deliverables

* [ ] Create `src/docs/index.md` with content `# Vulgar Project Development Life-Cycle`
...
```
````

* [ ] Review the [`policy-projects`](https://github.com/liquid-labs/policy-projects) documentation and identify sections which deal specifically with change control.
* [ ] Identify text blocks from `policy-projects` for extraction and plan out deliverable files and templates such that the Vulgar PDLC is both a standalone project development life cycle specification and also exports reusable template markdown files that can be included in larger works. Refer to the [abstraction and exports notes](#abstraction-and-exports) for further details.
* [ ] Identify and 
* [ ] Plan migration of the [project change flow](https://github.com/liquid-labs/policy-projects/blob/3e44a64d5a8a4c5050e1e7b18c1dbf0116ef48e4/policy/projects/project-change-flow.mmd) and [project lifecycle](https://github.com/liquid-labs/policy-projects/blob/3e44a64d5a8a4c5050e1e7b18c1dbf0116ef48e4/policy/projects/project-lifecycle.mmd) diagrams to this project. See [distribution notes](#distribution)
* [ ] Develop/plan method to create standalone Vulgar SDLC site using GitHub pages.
* [ ] Generate a `References.md` document which lists links to any material used in creating the task specs and which will inform our own content. For each reference, link the title of the referenced work to the current best URL for it and also include a brief explanatory text and the approximate date the work was reviewed. E.g.: `* [Google SDLC](http://docs.google.com/blah/blah/google-sdlc): a comprehensive example of a SDLC description; we adapt their definition of "project" and their [implementation flow](https://...) diagram. _(2021-10-01 by your-email@foo.com)_`
* [ ] You don't need to add all the bounty boilerplate to the task specced in the implementation plan, but do suggest what you think would be a fair bounty price for each.
* [ ] Note any dependencies between the task with a naked 'Depends on' line at the top of the task spec, before the 'Overview' seciton.

### Content and scope

It's not immediately clear how voluminous the documentation will end up being. We want to be fairly complete so that an organization could adopt the Vulgar PDLC and reasonably say "this is our project development life cycle specification" without needing to add or specify anything additional. Use your judgement. Whether this is a basic overview and a few key definitions, with maybe a supporting white paper or two, or if it's a bit more substantial is up to you.

Search out and review some other P/SDLCs and get a feel for their scope. Be sure and note anything you research and 

### Abstraction and exports

Not everything specified here needs to be exported back into `policy-projects`. Think of the `policy-projects` as a prototype consumer/customer of the Vulgar PDLC project. We'll want to embed the basic, key bits directly, but the Vulgar PLDC can also be incorporated by reference. For instance, fiddly technical specifications and background white papers and such are probably better referenced than directly incorporated.

### Project and source layout

The project will be setup as an NPM project. Consider creating and submitting an appropriate `package.json` with the project plan. If not, then be sure and specify the setup in the tasks.

Be sure and use the standard `src/` directory to house all the input code. I'm thinking we probably do:
* `src/docs` and
* `src/diagrams`

You can refer to the the existing policy projects such as [`policy-core`](https://github.com/liquid-labs/policy-core) for some idea of how the input markdown template files look. Notice that the project layout and naming conventions used in the policy projects are different than what we will do here. (We will update the policy project layouts eventually and, for instance, move the root `policy` directory to `src/docs`.

### Document format and conventions

All documents should be specified as basic markdown (`.md`) or template components (`.mdtmpl`) which define a template using go-doc format. These are processed processed by [gucci](https://github.com/noqcks/gucci) to produce final pure `.md` output for distribution (see [building notes](#building)). Note the 'mdtmpl' extensions is used for pure, single template files. I.e., each mdtmpl file should contain a single template definition. The top level md files will often contain elements and require processing into a final built/distributable form, but we still use the standard md extension in that case by convention.

Use mermaid (`.mmd`) for diagrams.

If a real need for something else is identified, discuss it in the issue comments.

Go templates should be named and referenced like, `vulgar_pdlc/doc_sub_dir/Document Name`. E.g., if we had a file `src/docs/implementation/Implementation Phase.mdtmpl` then we would expect that file to define a template named `vulgar_pdlc/implementation/Implementation Phase`.

### Distribution

The built distribution should support both a standalone site, version specific referenceable documents, and exported documents. Use [`gucci-wrapper`](https://github.com/liquid-labs/gucci-wrapper) (`npm i --save-dev @liquid-labs/gucci-wrapper`) and `mmd` (`npm i --save-dev mermaid`) to process the tools.

The build should be done using a Makefile, but also tie into the `package.json` scripts. E.g., `"scripts: { "build": "make"...` etc.

The policy projects are built using a tool specific to them (that we will probably abstract and use here later), but we're not going to use that here. For now, we can just manually create everything that needs to happen:

* Exportable templates and diagrams should be copied to `dist/templates` (or...?) and `dist/diagrams` respectively.
* Include light (neutral) and dark PNG renderings in `dist/diagrams`.
* `dist/docs` will be committed and version so that external technical references can specify a particular release. E.g., they would link to `https://github.com/liquid-labs/vulgar-pdlc/tree/v1.3.1/dist/docs/index.md`
* `dist/docs` will also (I'm thinking) be the root of the GitHub site, which will be a reference for the most current released site. It may be useful to specify a branch to build the GitHub page from as well since the `main` branch will sometimes reflect merged but pre-release changes.

### Building

Whether or not you work on the implementation (after planning is complete), you can incorporate these notes into the proper task specs.

#### Template processing with gucci

[gucci GitHub page](https://github.com/noqcks/gucci)

When using gucci, it's necessary to feed all go-style template data into a page that uses it. For instance, if we had `index.md` which is our overview/front page for the Vulgar PDLC docs, and that references a template for the overview like:

```markdown
# Vulgar Project Development Life Cycle

## Overview

{{ template "vulgar_pdlc/Vulgar PDLC Summary" . }}
```

And we had a file `src/docs/Vulgar PDLC summary.mdtmpl` like:
```
{{ define "vulgar_pdlc/Vulgar PDLC summary" -}}
The Vulgar PDLC is awesome!
{{- end }}
```

Then we would build the output file with something like:

```Makefile
GUCCI=$(shell npm bin)/gucci

dist/docs/index.md: src/docs/index.md src/docs/Vulgar\ PDLC\ Summary.mdtmpl
	cat $^ | $(GUCCI) --vars-file src/docs/settings.yaml > $@
```

Which basically says "to build the final `index.md`, we feed gucci the source `index.md` as well as all the necessary templates and the output of that is the final `index.md`." Note the `$^` means 'all prerequisites'.

Also, note we demonstrate using a vars file here. It's not necessary, but if you come across any data items that seem good candidates for parameterization, go ahead and specify use of a `settings.yaml` for those.

#### Diagram placement

In order to support correct linking and rendering when rendering final documents from `dist/docs` and also the GitHub pages site, I think placing all the published diagrams in `dist/docs/diagrams` and then using relative links to the images should work in both cases.
